[package]
name = "orchestrator-worker-eventbus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
orchestrator-worker-protocol = { path = "../orchestrator-worker-protocol" }
tokio = { workspace = true }
