[package]
name = "orchestrator-vcs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
orchestrator-core = { path = "../orchestrator-core" }
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
