[package]
name = "integration-git"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
orchestrator-core = { path = "../orchestrator-core" }
async-trait.workspace = true

[dev-dependencies]
tokio.workspace = true
